## druid的配置，请参考官方链接：https://github.com/alibaba/druid/wiki/
server:
  servlet:
    context-path: /xiyou
mybatis:
  mapper-locations: classpath:/mapper/*xml

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    ## mysql8.0用这个
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/hcg?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
